@rpgAPI_HostAddress = https://localhost:7064
@id = 1

GET {{rpgAPI_HostAddress}}/api/Character/
Accept: application/json

###


### Update Character
PUT {{rpgAPI_HostAddress}}/api/Character/UpdateCharacter


### Delete Character
DELETE {{rpgAPI_HostAddress}}/api/Character/DeleteCharacter/{{id}}